#!/bin/bash
#PBS -l  nodes=1:ppn=1,walltime=10:00
#PBS -N atumohanjob
#PBS -m abe
#PBS -M atumohan@iu.edu
#PBS -e /N/dc2/scratch/atumohan/atumohanjob.err
#PBS -o /N/dc2/scratch/atumohan/atumohanjob.log
cd /N/dc2/scratch/atumohan/
chmod 777 /N/dc2/scratch/atumohan/
./a.c.out
echo "The log files are attached"|mailx -r Zenith -s"Karst execution results" -a /N/dc2/scratch/atumohan/atumohanjob.err -a /N/dc2/scratch/atumohan/atumohanjob.log "atumohan@iu.edu"
echo "The log files are attached"|mailx -r Zenith -s"Karst execution results" -a /N/dc2/scratch/atumohan/atumohanjob.err -a /N/dc2/scratch/atumohan/atumohanjob.log "atumohan@iu.edu"
zip atumohanjob.zip /N/dc2/scratch/atumohan/atumohanjob.err /N/dc2/scratch/atumohan/atumohanjob.log 1> /dev/null
