#!/bin/bash
#PBS -l  nodes=1:ppn=1,walltime=10:00
#PBS -N Testjob23
#PBS -m abe
#PBS -M atumohan@iu.edu
#PBS -e /N/dc2/scratch/atumohan/Testjob23.err
#PBS -o /N/dc2/scratch/atumohan/Testjob23.log
cd /N/dc2/scratch/atumohan/
chmod 777 /N/dc2/scratch/atumohan/
./a.c.out
echo "The log files are attached"|mailx -r Zenith -s"Karst execution results" -a /N/dc2/scratch/atumohan/Testjob23.err -a /N/dc2/scratch/atumohan/Testjob23.log "atumohan@iu.edu"
echo "The log files are attached"|mailx -r Zenith -s"Karst execution results" -a /N/dc2/scratch/atumohan/Testjob23.err -a /N/dc2/scratch/atumohan/Testjob23.log "atumohan@iu.edu"
zip Testjob23.zip /N/dc2/scratch/atumohan/Testjob23.err /N/dc2/scratch/atumohan/Testjob23.log 1> /dev/null
