#!/bin/bash
#PBS -l  nodes=1:ppn=1,walltime=10:00
#PBS -N cutozzqq
#PBS -m abe
#PBS -M atumohan@iu.edu
#PBS -e /N/dc2/scratch/atumohan/cutozzqq.err
#PBS -o /N/dc2/scratch/atumohan/cutozzqq.log
cd /N/dc2/scratch/atumohan/
chmod 777 /N/dc2/scratch/atumohan/
./b.c.out
echo "The log files are attached"|mailx -r Zenith -s"Karst execution results" -a /N/dc2/scratch/atumohan/cutozzqq.err -a /N/dc2/scratch/atumohan/cutozzqq.log "atumohan@iu.edu"
echo "The log files are attached"|mailx -r Zenith -s"Karst execution results" -a /N/dc2/scratch/atumohan/cutozzqq.err -a /N/dc2/scratch/atumohan/cutozzqq.log "atumohan@iu.edu"
zip cutozzqq.zip /N/dc2/scratch/atumohan/cutozzqq.err /N/dc2/scratch/atumohan/cutozzqq.log 1> /dev/null
