#!/bin/bash
#PBS -l  nodes=1:ppn=1,walltime=10:00
#PBS -N tyuo9911
#PBS -m abe
#PBS -M atumohan@iu.edu
#PBS -e /N/dc2/scratch/atumohan/tyuo9911.err
#PBS -o /N/dc2/scratch/atumohan/tyuo9911.log
cd /N/dc2/scratch/atumohan/
chmod 777 /N/dc2/scratch/atumohan/
aprun -n 16  a.c.out
echo "The log files are attached"|mailx -r Zenith -s"Karst execution results" -a /N/dc2/scratch/atumohan/tyuo9911.err -a /N/dc2/scratch/atumohan/tyuo9911.log "atumohan@iu.edu"
echo "The log files are attached"|mailx -r Zenith -s"Karst execution results" -a /N/dc2/scratch/atumohan/tyuo9911.err -a /N/dc2/scratch/atumohan/tyuo9911.log "atumohan@iu.edu"
zip tyuo9911.zip /N/dc2/scratch/atumohan/tyuo9911.err /N/dc2/scratch/atumohan/tyuo9911.log 1> /dev/null
